# Generated by Django 4.2.7 on 2025-10-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_module_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='live_class_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
