# Generated by Django 4.2.7 on 2025-10-17 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.CharField(default='Semicolons Team', max_length=100),
        ),
    ]
