# Generated by Django 4.2.7 on 2025-10-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_course_instructor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='instructor',
        ),
        migrations.AddField(
            model_name='course',
            name='live_class_time',
            field=models.CharField(blank=True, help_text='e.g., 8:00 PM BDT', max_length=100, null=True),
        ),
    ]
